platform :ios, '15.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

prepare_react_native_project!

target 'ReactNative' do
  config = use_native_modules!

  # Configuración predeterminada para React Native y sus módulos
  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Incluir RNPermissions
  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  # Agregar permisos de react-native-permissions
  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"

  target 'ReactNativeTests' do
    inherit! :complete
    # Dependencias para pruebas
  end

  post_install do |installer|
    react_native_post_install(installer)
  end
end
